### ISSUE TITLE
add support for any bigquery auth method - not just service account

### ISSUE THREAD

**Issue by adamcunnington-mlg** [preset-io/backend-sdk#202] opened 2023-04-28 20:58 UTC
Currently, only the `service-account` method with `keyfile` present is supported. You can't use the `sync dbt-core` command without using this strict method. I don't see why not. Why can't I use oauth? in CI, as well as local, we make use of oauth for security reasons. Why does preset have an opinion of the auth method. It should piggy back dbt's support.

**Comment by Vitor-Avila** [comment] 2023-04-28 21:11
Hi @adamcunnington-mlg, 

As part of the sync process, the CLI would create datasets in Preset corresponding to your dbt models. In order for these datasets to work, they should be associated with a working database connection (in Preset). 

When the sync is configured to create/update the db connection (by using the `--import-db` flag), the CLI would create the connection in your Preset Workspace based on the `profiles.yml` configuration. However, it's only possible to connect Preset to BigQuery DB using JSON/keyfile:
* [How to connect Google BQ DB to Preset](https://docs.preset.io/docs/big-query-database)

This would actually be a limitation in the Preset side. 

Note that you can configure the DB connection directly in Preset, and then trigger a dbt sync without the `--import-db` command. This would avoid the operation from creating/updating the database connection, and therefore the unsupported authentication method for Preset used in dbt wouldn't be a blocker.

You can specify the database connection that should be used in Preset directly in your `profiles.yml` file. For example:
``` yaml
jaffle_shop:
  outputs:
    dev:
      meta:
        superset:
          database_name: BQ DB
```

Use the connection display name from Preset in the `database_name` value.

Let me know if you have any questions.

**Comment by adamcunnington-mlg** [comment] 2023-04-28 22:44
@Vitor-Avila I am doing exactly that - using existing connection. I don't provide --import-db but service-account still required.

**Comment by adamcunnington-mlg** [comment] 2023-04-28 22:46
@Vitor-Avila ah, red herring. I see that this was fixed in a recent PR and if I install from main, all is good.

Why is preset-cli not being released in pypi? There are lots of critical bug fixes since February last year yet the version on pypi is still September? Does this project not have proper release process?

**Comment by Vitor-Avila** [comment] 2023-05-02 19:07
Hey @adamcunnington-mlg, 

Thanks for confirming the issue is solved when installing it from the repository. I'm going to share your feedback internally and work with our Engineering team to perform a new release -- at the moment we don't have a defined release schedule for the CLI package.

I'm going to close this issue. In the future, I would recommend reaching out through the Preset Support Portal instead, to ensure SLA response times.

**Closed by Vitor-Avila** 2023-05-02 19:07 UTC
